version: "3.9"

services:
  node-red:
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=Asia/Singapore
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 1880:1880
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
      - ./certs/cert.pem:/etc/nginx/certs/cert.pem
      - ./certs/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - node-red
    command: ["nginx", "-g", "daemon off;"]

volumes:
  node-red-data:

networks:
  default:
